spring:
  application:
    name: aimin-gateway
  cloud:
    nacos:
      discovery:
        namespace: ba2e7f3d-23a3-4bf1-a8f5-6a5dfce1c259
      server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: aimin-auth
          uri: lb://aimin-auth
          predicates:
            - Path=/aimin-auth/**
        - id: aimin-ai
          uri: lb://aimin-ai
          predicates:
              - Path=/aimin-ai/**



server:
  port: 8080
  servlet:
    context-path: /aimin-ai  # listen tcp 127.0.0.1:11434
